describe('Authentication', () => {
    it('verify valid address', () => {
        cy.visit('/login')
        cy.get('input[type=email]').type('rfvedcqwsx12@live.com')
        cy.get('input[type=password]').type('qwer1234')
        cy.contains('button', /^Login$/).click()
        cy.url().should('include', '/verify')
        cy.get('input[name=postcode]').type('3006')
        cy.get('input[name=suburb]').type('Southbank')
        cy.get('select[name=state]').select('VIC')    
        cy.contains('button', /^Verify Address$/).click()
        cy.contains('button', /^Verify Address$/).should('not.exist')
        cy.contains('button', /^Verifying...$/).should('not.exist')
        cy.contains('The postcode, suburb, and state input are valid.')

    })
    it('verify invalid postcode', () => {
        cy.visit('/login')
        cy.get('input[type=email]').type('rfvedcqwsx12@live.com')
        cy.get('input[type=password]').type('qwer1234')
        cy.contains('button', /^Login$/).click()
        cy.url().should('include', '/verify')
        cy.get('input[name=postcode]').type('3005')
        cy.get('input[name=suburb]').type('Southbank')
        cy.get('select[name=state]').select('VIC')    
        cy.contains('button', /^Verify Address$/).click()
        cy.contains('button', /^Verify Address$/).should('not.exist')
        cy.contains('button', /^Verifying...$/).should('not.exist')
        cy.contains('The postcode 3005 does not match the suburb Southbank.')

    })
    it('verify invalid suburb', () => {
        cy.visit('/login')
        cy.get('input[type=email]').type('rfvedcqwsx12@live.com')
        cy.get('input[type=password]').type('qwer1234')
        cy.contains('button', /^Login$/).click()
        cy.url().should('include', '/verify')
        cy.get('input[name=postcode]').type('3006')
        cy.get('input[name=suburb]').type('Southbank')
        cy.get('select[name=state]').select('NSW')    
        cy.contains('button', /^Verify Address$/).click()
        cy.contains('button', /^Verify Address$/).should('not.exist')
        cy.contains('button', /^Verifying...$/).should('not.exist')
        cy.contains('The suburb Southbank does not exist in the state NSW.')

    })
})